import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function POST(req: Request) {
  try {
    const { batchId } = await req.json();

    if (!batchId) {
      return NextResponse.json({ error: "Batch ID is required" }, { status: 400 });
    }

    // 更新批次状态为处理中
    await prisma.importBatch.update({
      where: { id: batchId },
      data: { status: "PROCESSING" },
    });

    // 实际工程中，这里应该是一个异步任务推送到队列（如 Inngest / Kafka / Redis List）
    // 为了可开发演示，我们直接在后台模拟一个异步处理
    processBatchAsync(batchId);

    return NextResponse.json({ 
      success: true, 
      message: "Parsing started", 
      batchId 
    });
  } catch (error) {
    console.error("Parse Error:", error);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}

// 模拟异步的 CSV 解析与 AI 清洗
async function processBatchAsync(batchId: string) {
  try {
    // 假设我们解析出了 10 条数据
    const totalCount = 10;
    
    // Simulate parsing delay
    await new Promise((resolve) => setTimeout(resolve, 2000));

    // 这边本来应该调用第三方大模型接口（如 OpenAI / Anthropic）提取结构化数据
    // ...

    // 假设成功处理，存入数据库
    for (let i = 0; i < totalCount; i++) {
        await prisma.product.create({
            data: {
                name: `Parsed Product ${i}`,
                slug: `parsed-product-${batchId}-${i}`, // Required field in schema
                summary: `This is a summary for product ${i} generated by AI`, // Required field
                boxType: "MAILER_BOX", // Required field
                productCode: `SKU-BATCH-${batchId}-${i}`,
                attributes: {
                    material: "300gsm Kraft Paper",
                    color: "Brown",
                    printing: "CMYK"
                },
                aiTags: ["Kraft", "Eco-friendly", "Custom"],
                aiSummary: "The perfect custom kraft paper box for your brand.",
                status: "NEEDS_REVIEW"
            }
        });
    }

    await prisma.importBatch.update({
      where: { id: batchId },
      data: { 
        status: "COMPLETED",
        totalCount,
        successCount: totalCount
      },
    });
  } catch (error) {
    console.error(`Batch ${batchId} failed:`, error);
    await prisma.importBatch.update({
      where: { id: batchId },
      data: { 
        status: "FAILED",
        errorLogs: { error: String(error) }
      },
    });
  }
}
